DECLARE @T TABLE(CustomerID INT);

MERGE 
    INTO tblCustomers AS TARGET
    USING tblCustomersStage AS SOURCE
    ON TARGET.CustomerID = SOURCE.CustomerID
    WHEN MATCHED
        THEN UPDATE SET 
			[ShortName] = SOURCE.[ShortName], 
			[FullName] = SOURCE.[FullName],
			[FirstName] = SOURCE.[FirstName],
			[MiddleName] = SOURCE.[MiddleName],
			[Callsign] = SOURCE.[Callsign],
			[LastName] = SOURCE.[LastName],
			[Notes] = SOURCE.[Notes],
			[email] = SOURCE.[email],
			[Phone1] = SOURCE.[Phone1],
			[ShipStreetAddress1] = SOURCE.[ShipStreetAddress1],
			[ShipStreetAddress2] = SOURCE.[ShipStreetAddress2],
			[ShipCity] = SOURCE.[ShipCity],
			[ShipState] = SOURCE.[ShipState],
			[ShipZip] = SOURCE.[ShipZip],
			[WingingDate] = SOURCE.[WingingDate],
			[InstrumentRated] = SOURCE.[InstrumentRated],
			[MultiCrewPIC] = SOURCE.[MultiCrewPIC],
			[SoloDate] = SOURCE.[SoloDate],
			[Military] = SOURCE.[Military],
			[MilitaryBranch] = SOURCE.[MilitaryBranch],
			[AV8BHarrier] = SOURCE.[AV8BHarrier],
			[V22Osprey] = SOURCE.[V22Osprey],
			[TRACOMIP] = SOURCE.[TRACOMIP],
			[CommercialFiles] = SOURCE.[CommercialFiles],
			[Part121FlightRecords] = SOURCE.[Part121FlightRecords],
			[AirlineFliesFor] = SOURCE.[AirlineFliesFor],
			[CorporateFiles] = SOURCE.[CorporateFiles],
			[ContractorFiles] = SOURCE.[ContractorFiles],
			[ContractorFliesFor] = SOURCE.[ContractorFliesFor],
			[GALogbooks] = SOURCE.[GALogbooks],
			[FAAPilotCert] = SOURCE.[FAAPilotCert],
			[PPLDate] = SOURCE.[PPLDate],
			[CPLDate] = SOURCE.[CPLDate],
			[ATPDate] = SOURCE.[ATPDate],
			[CFIDate] = SOURCE.[CFIDate],
			[CFIIDate] = SOURCE.[CFIIDate],
			[MEIDate] = SOURCE.[MEIDate],
			[MEIIDate] = SOURCE.[MEIIDate],
			[HeardAboutUs] = SOURCE.[HeardAboutUs],
			[RegisterDateTime] = SOURCE.[RegisterDateTime],
			[TypeofLogbooks] = SOURCE.[TypeofLogbooks],
			[RATPRequest] = SOURCE.[RATPRequest],
			[Expedite] = SOURCE.[Expedite],
			[QAby] = SOURCE.[QAby],
			[QACost] = SOURCE.[QACost],
			[SentToOutsource] = SOURCE.[SentToOutsource],
			[ReceivedForm] = SOURCE.[ReceivedForm],
			[SentProduct] = SOURCE.[SentProduct],
			[Charged] = SOURCE.[Charged],
			[PaymentCollected] = SOURCE.[PaymentCollected],
			[BinderPurchased] = SOURCE.[BinderPurchased],
			[ShipNormal] = SOURCE.[ShipNormal],
			[ShipOvernight] = SOURCE.[ShipOvernight],
			[MailingBinderCost] = SOURCE.[MailingBinderCost],
			[BinderSent] = SOURCE.[BinderSent],
			[TotalCost] = SOURCE.[TotalCost],
			[Profit] = SOURCE.[Profit],
			[version] = SOURCE.[version],
			[LastUpdate] = SOURCE.[LastUpdate],
			[InterviewDate] = SOURCE.[InterviewDate],
			[InterviewAirline] = SOURCE.[InterviewAirline],
			[AirlineNotes] = SOURCE.[AirlineNotes],
			[ScannedBy] = SOURCE.[ScannedBy],
			[ScannerCost] = SOURCE.[ScannerCost],
			[FirstOutputDate] = SOURCE.[FirstOutputDate],
			[BirdEyeReviewSent] = SOURCE.[BirdEyeReviewSent],
			[BirdEyeReviewReceived] = SOURCE.[BirdEyeReviewReceived],
			[Outsource] = SOURCE.[Outsource],
			[CostPerLine] = SOURCE.[CostPerLine],
			[POC] = SOURCE.[POC],
			[NavyPages] = SOURCE.[NavyPages],
			[NavyLines] = SOURCE.[NavyLines],
			[GAsmallPages] = SOURCE.[GAsmallPages],
			[GAsmallLines] = SOURCE.[GAsmallLines],
			[GAlargePages] = SOURCE.[GAlargePages],
			[GAlargeLines] = SOURCE.[GAlargeLines],
			[USAFPages] = SOURCE.[USAFPages],
			[USAFLines] = SOURCE.[USAFLines],
			[OutsourceSent] = SOURCE.[OutsourceSent],
			[OutsourceReceived] = SOURCE.[OutsourceReceived],
			[OutsourceDueDate] = SOURCE.[OutsourceDueDate],
			[CompletionDays] = SOURCE.[CompletionDays],
			[OutsourceCost] = SOURCE.[OutsourceCost]
    WHEN NOT MATCHED BY TARGET
        THEN INSERT 
			([CustomerID],
			[ShortName],
			[FullName],
			[FirstName],
			[MiddleName],
			[Callsign],
			[LastName],
			[Notes],
			[email],
			[Phone1],
			[ShipStreetAddress1],
			[ShipStreetAddress2],
			[ShipCity],
			[ShipState],
			[ShipZip],
			[WingingDate],
			[InstrumentRated],
			[MultiCrewPIC],
			[SoloDate],
			[Military],
			[MilitaryBranch],
			[AV8BHarrier],
			[V22Osprey],
			[TRACOMIP],
			[CommercialFiles],
			[Part121FlightRecords],
			[AirlineFliesFor],
			[CorporateFiles],
			[ContractorFiles],
			[ContractorFliesFor],
			[GALogbooks],
			[FAAPilotCert],
			[PPLDate],
			[CPLDate],
			[ATPDate],
			[CFIDate],
			[CFIIDate],
			[MEIDate],
			[MEIIDate],
			[HeardAboutUs],
			[RegisterDateTime],
			[TypeofLogbooks],
			[RATPRequest],
			[Expedite],
			[QAby],
			[QACost],
			[SentToOutsource],
			[ReceivedForm],
			[SentProduct],
			[Charged],
			[PaymentCollected],
			[BinderPurchased],
			[ShipNormal],
			[ShipOvernight],
			[MailingBinderCost],
			[BinderSent],
			[TotalCost],
			[Profit],
			[version],
			[LastUpdate],
			[InterviewDate],
			[InterviewAirline],
			[AirlineNotes],
			[ScannedBy],
			[ScannerCost],
			[FirstOutputDate],
			[BirdEyeReviewSent],
			[BirdEyeReviewReceived],
			[Outsource],
			[CostPerLine],
			[POC],
			[NavyPages],
			[NavyLines],
			[GAsmallPages],
			[GAsmallLines],
			[GAlargePages],
			[GAlargeLines],
			[USAFPages],
			[USAFLines],
			[OutsourceSent],
			[OutsourceReceived],
			[OutsourceDueDate],
			[CompletionDays],
			[OutsourceCost])
    VALUES 
		(SOURCE.[CustomerID],
		SOURCE.[ShortName],
		SOURCE.[FullName],
		SOURCE.[FirstName],
		SOURCE.[MiddleName],
		SOURCE.[Callsign],
		SOURCE.[LastName],
		SOURCE.[Notes],
		SOURCE.[email],
		SOURCE.[Phone1],
        SOURCE.[ShipStreetAddress1],
        SOURCE.[ShipStreetAddress2],
        SOURCE.[ShipCity],
        SOURCE.[ShipState],
        SOURCE.[ShipZip],
        SOURCE.[WingingDate],
        SOURCE.[InstrumentRated],
        SOURCE.[MultiCrewPIC],
        SOURCE.[SoloDate],
        SOURCE.[Military],
        SOURCE.[MilitaryBranch],
        SOURCE.[AV8BHarrier],
        SOURCE.[V22Osprey],
        SOURCE.[TRACOMIP],
        SOURCE.[CommercialFiles],
        SOURCE.[Part121FlightRecords],
        SOURCE.[AirlineFliesFor],
        SOURCE.[CorporateFiles],
        SOURCE.[ContractorFiles],
        SOURCE.[ContractorFliesFor],
        SOURCE.[GALogbooks],
        SOURCE.[FAAPilotCert],
        SOURCE.[PPLDate],
        SOURCE.[CPLDate],
        SOURCE.[ATPDate],
        SOURCE.[CFIDate],
        SOURCE.[CFIIDate],
        SOURCE.[MEIDate],
        SOURCE.[MEIIDate],
        SOURCE.[HeardAboutUs],
        SOURCE.[RegisterDateTime],
        SOURCE.[TypeofLogbooks],
        SOURCE.[RATPRequest],
        SOURCE.[Expedite],
        SOURCE.[QAby],
        SOURCE.[QACost],
        SOURCE.[SentToOutsource],
        SOURCE.[ReceivedForm],
        SOURCE.[SentProduct],
        SOURCE.[Charged],
        SOURCE.[PaymentCollected],
        SOURCE.[BinderPurchased],
        SOURCE.[ShipNormal],
        SOURCE.[ShipOvernight],
        SOURCE.[MailingBinderCost],
        SOURCE.[BinderSent],
        SOURCE.[TotalCost],
        SOURCE.[Profit],
        SOURCE.[version],
        SOURCE.[LastUpdate],
        SOURCE.[InterviewDate],
        SOURCE.[InterviewAirline],
        SOURCE.[AirlineNotes],
        SOURCE.[ScannedBy],
        SOURCE.[ScannerCost],
        SOURCE.[FirstOutputDate],
        SOURCE.[BirdEyeReviewSent],
        SOURCE.[BirdEyeReviewReceived],
        SOURCE.[Outsource],
        SOURCE.[CostPerLine],
        SOURCE.[POC],
        SOURCE.[NavyPages],
        SOURCE.[NavyLines],
        SOURCE.[GAsmallPages],
        SOURCE.[GAsmallLines],
        SOURCE.[GAlargePages],
        SOURCE.[GAlargeLines],
        SOURCE.[USAFPages],
        SOURCE.[USAFLines],
        SOURCE.[OutsourceSent],
        SOURCE.[OutsourceReceived],
        SOURCE.[OutsourceDueDate],
        SOURCE.[CompletionDays],
        SOURCE.[OutsourceCost])
OUTPUT SOURCE.CustomerID INTO @T;

DELETE dbo.tblCustomersStage
	WHERE CustomerID in (SELECT CustomerID
						 FROM @T);